[package]
name = "tui-logger"
version = "0.4.5"
authors = ["Jochen Kiemes <jochen@kiemes.de>"]
edition = "2018"
license = "MIT"
description = "Logger with smart widget for the `tui` crate"
documentation = "https://docs.rs/tui-logger/0.4.4/tui_logger/"
repository = "https://github.com/gin66/tui-logger"
readme = "README.md"
keywords = ["tui", "log", "logger", "widget", "dispatcher"]

[badges]
travis-ci = { repository = "gin66/tui-logger" }

[features]
default = ["tui-crossterm"]
tui-termion = ["tui/termion", "termion"]
tui-crossterm = ["tui/crossterm", "crossterm"]

[dependencies]
log = "0.4"
chrono = "0.4"
tui = { version = "0.9", default-features = false }
crossterm = { version = "*", optional = true }
termion = { version = "1.5", optional = true }
lazy_static = "1.0"
fxhash = "0.2"
parking_lot = "0.10"
